variables:
    IMAGE_NAME: son162001/manage-graduation-thesis-iuh
    IMAGE_TAG: latestnode:latest

stages:
    # - test
    - build
    # - deploy

# run_tests:
#     stage: test
#     image: node:16.16.0-alpine
#     script:
#         - echo "test"

build:
    stage: build
    before_script:
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
        - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "git@gitlab.com:nguyenthanhson162001/manage-graduation-thesis-iuh-be.git || true"
        - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "cd manage-graduation-thesis-iuh-be && git pull"
        - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "cd manage-graduation-thesis-iuh-be && npm i"
        - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "cd manage-graduation-thesis-iuh-be && npm run build"
        - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "cd manage-graduation-thesis-iuh-be && (npm start || true)"
        - echo "Application successfully deployed."
    only:
        - master
# deploy:
#     stage: deploy
#     before_script:
#         - echo $SSH_PRIVATE_KEY
#         - chmod 400 $SSH_PRIVATE_KEY
#     script:
#         - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@ec2-3-0-102-80.ap-southeast-1.compute.amazonaws.com "
#           ./script.sh"
# deploy:
#     stage: deploy
#     image: alpine
#     before_script:
#         - apk add openssh-client
#         - eval $(ssh-agent -s)
#         - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#         - mkdir -p ~/.ssh
#         - chmod 700 ~/.ssh
#     script:
#         - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "git@gitlab.com:nguyenthanhson162001/manage-graduation-thesis-iuh-be.git || true"
#         - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "cd demo-cicd && git pull"
#         - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "cd demo-cicd && npm i"
#         - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS "cd demo-cicd && (npm start || true)"
#         - echo "Application successfully deployed."
